# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "029bbcc52e1a61e72ba0ca1b552021ee"
organization_id = "159106160"
name = "customer-accounts-2025-1"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,customer_write_customers,write_customers,customer_read_orders,unauthenticated_read_product_listings,unauthenticated_read_product_publications,unauthenticated_read_product_tags,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[customer.metafields.app.wishlist-items]
type = "list.product_reference"
name = "Wishlist items"
description = "Wishlist items for a customer"

  [customer.metafields.app.wishlist-items.access]
  customer_account = "read_write"
